Frontend
CS3219-AY2223S1/cs3219-project-ay2223s1-g45 pull request #36
Opened 2022-09-13 09:36 UTC by adidoesnt

2022-09-13 10:05 UTC, aizatazhar requested changes

2022-09-13 10:05 UTC, aizatazhar commented on apps/frontend/src/components/LobbyPage.tsx
> +          <Input
add `onKeyPress` event so that message is sent when user hits enter on keyboard
https://stackoverflow.com/a/69908211

2022-09-13 10:17 UTC, aizatazhar commented on apps/frontend/src/components/SettingsPage.tsx
>    const setErrorDialog = (msg: any) => {
we should try to not use any otherwise it defeats the purpose of typescript

2022-09-13 10:18 UTC, aizatazhar commented on apps/frontend/src/components/SettingsPage.tsx
> +          {isDialogButtonEnabled ? (
A cleaner way to write this is isDialogButtonEnabled && <Box...
https://dev.to/harlessmark/short-circuit-evaluation-with-react-3dn4

2022-09-13 10:19 UTC, aizatazhar commented on apps/frontend/src/components/SettingsPage.tsx
> +              {isDialogInputEnabled ? (
A cleaner way to write this is `isDialogInputEnabled && <Box...`
https://dev.to/harlessmark/short-circuit-evaluation-with-react-3dn4

2022-09-14 11:08 UTC, adidoesnt commented
ready for another review

2022-09-15 11:06 UTC, aizatazhar commented
in general it is a best practice to have small PRs as it makes it a lot easier to review amongst other benefits. here is a short read  https://google.github.io/eng-practices/review/developer/small-cls.html

2022-09-15 13:36 UTC, aizatazhar approved these changes

2022-09-15 13:46 UTC, Jonathan-Cao commented on apps/frontend/src/components/ChangePasswordPage.tsx
> +          { withCredentials: true }
![image](https://user-images.githubusercontent.com/54720093/190419586-1fafa676-2e2a-4a96-9dff-bbe49aad6870.png)
From what I understand, the request body and axios request config are separate parameters.

2022-09-15 16:52 UTC, merged